name: Deploy Nuxt2 Static Site to S3

on:
  workflow_dispatch:
  push:
    branches:
      - main          

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: nuxt2-migration-sample/package-lock.json

      - name: Install Dependencies
        working-directory: ./nuxt2-migration-sample
        run: npm ci

      - name: Generate Static Site
        working-directory: ./nuxt2-migration-sample
        run: npm run generate:static

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync ./nuxt2-migration-sample/dist/ s3://sd-nuxt2-static-poc --delete

      - name: Deployment Complete
        run: echo "Deployment Successful!"
